name: Build
on: 
 push:
  branches:
   - release/weather-web

jobs:
  publishplanningcenterorto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build And Deploy Weather Web
        id: builddeployWeatherWeb
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_WEATHER }}
          action: "upload"
          app_location: "/"
          output_location: "build"